version: '3.3'
services:
  myDb:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_pwd
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - my-net
networks:
  my-net: null