version: '3.7'
services:
  myDb:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_pwd
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - my-net
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mydb
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    networks:
      - my-net
volumes:
  my-db: null
networks:
  my-net: null